version: "3.9"
services:

  db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: "unless-stopped"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: "unless-stopped"

volumes:
  app-db-data:
