# Generated by Django 4.0 on 2021-12-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionSyncrhonization',
            new_name='TransactionSynchronization',
        ),
        migrations.AlterModelTable(
            name='transactionsynchronization',
            table='transaction_syncrhonization',
        ),
    ]
