# Generated by Django 4.0 on 2021-12-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactionsynchronization',
            table='transaction_synchronization',
        ),
    ]
