# Generated by Django 4.0 on 2022-01-02 18:16

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transactionsynchronization_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('balance', models.JSONField(default=tracker.models.jsonfield_default_value)),
                ('crystal_log', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_hash', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=100)),
                ('address_from', models.CharField(max_length=1024)),
                ('address_to', models.CharField(max_length=1024)),
                ('function', models.CharField(max_length=128)),
                ('transaction_fee', models.FloatField()),
                ('token_transaction', models.JSONField(null=True)),
                ('hero_transaction', models.JSONField(null=True)),
                ('lp_transaction', models.JSONField(null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.wallet')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
