# Generated by Django 4.0 on 2021-12-30 16:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transactionsynchronization_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField()),
                ('wallet_address', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('tokens', jsonfield.fields.JSONField()),
                ('heroes', jsonfield.fields.JSONField()),
                ('lp_balance', jsonfield.fields.JSONField()),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_hash', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('transaction_timestamp', models.DateTimeField()),
                ('address_from', models.CharField(max_length=1024)),
                ('address_to', models.CharField(max_length=1024)),
                ('function', models.CharField(max_length=128)),
                ('transaction_fee', models.FloatField()),
                ('token_transaction', jsonfield.fields.JSONField()),
                ('hero_transaction', jsonfield.fields.JSONField()),
                ('lp_transaction', jsonfield.fields.JSONField()),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.wallet')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
