# Generated by Django 4.0 on 2022-01-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_mapped',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_mapped',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
