# Generated by Django 4.0 on 2021-12-30 17:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_wallet_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='heroes',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='lp_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='tokens',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=jsonfield.fields.JSONField(default={'heroes': {}, 'liquidity_pools': {}, 'tokens': {}}),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hero_transaction',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lp_transaction',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_transaction',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
